version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app/
    environment:
      - DATABASE_URL=postgres://postgres:password@database:5432/postgres
      - DEFAULT_URL=https://holis.com
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    depends_on:
      - database

  database:
    image: postgres:13.4
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:6.2.5-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/usr/src/app/
    depends_on:
      - database
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@database:5432/postgres
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

volumes:
  dbdata:
  redis_data:
